server:
  port: 0

spring:
  application:
    name: vacancy-scan-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: rabbitmq

rabbitmq:
  scheduled-task-queue: scheduled-tasks-queue

search:
  url: https://api.hh.ru/vacancies