server:
  port: 8021

spring:
  application:
    name: vacancy-scan-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: rabbitmq

rabbitmq:
  exchange: direct-exchange
  listen-queue: scheduled-tasks-queue
  routing-key: vacancy-save-key

search:
  url: https://api.hh.ru
  path: vacancies

executors:
  threads:
    scheduled: 1

rate-limiter:
  bucket-name: "vacancy-scan-service"