server:
  port: 0

spring:
  application:
    name: vacancy-scan-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: rabbitmq

rabbitmq:
  exchange: job-scanner-exchange
  scheduled-task-queue: scheduled-tasks-queue
  routing-key: vacancy-storage-key

search:
  url: https://api.hh.ru/vacancies