server:
  error:
    include-message: always
  port: 8081

spring:
  application:
    name: web-ui
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888
  profiles:
    active: dev