server:
  error:
    include-message: always
  port: 8081

spring:
  application:
    name: web-ui
  mvc:
    hiddenmethod:
      filter:
        enabled: true

cookie:
  remove-access-token:
    name: access_token
    value: null
    path: /
    expry: 0

page:
  request:
    pageNumber: 0
    pageSize: 3