server:
  port: 0

spring:
  application:
    name: analytic-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active:
      - rabbitmq
      - redis
      - postgresql

rabbitmq:
  listen-queue: vacancy-analytics-queue

page-request:
  batch-size: 1000