server:
  port: 0

spring:
  application:
    name: scheduler-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: rabbitmq

rabbitmq:
  exchange:
    name: job-scanner-exchange
    routing-key: scheduled-key

scheduler:
  fixed-rate: 10