server:
  port: 0

spring:
  application:
    name: scheduler-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active:
    - postgresql
    - rabbitmq

rabbitmq:
  exchange: direct-exchange
  routing-key: scheduled-key

scheduler:
  fixed-rate: 30
  batch-size: 1000