server:
  port: 0

spring:
  application:
    name: scheduler-service
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888
  profiles:
    active:
    - postgresql
    - rabbitmq
    - dev

rabbitmq:
  exchange: direct-exchange
  vacancy-scan-key: scheduled-key
  analytics-key: vacancy-analytics-key