server:
  port: 0

spring:
  application:
    name: scheduler-service
  rabbitmq:
    username: user
    password: pass

rabbitmq:
  exchange:
    name: job-scanner-exchange
    routing-key: scheduled-key

scheduler:
  fixed-rate: 10