server:
  port: 0

spring:
  application:
    name: vacancy-storage-service
  data:
    redis:
      host: localhost
      port: 6379
      password: pass
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: rabbitmq
  cache:
    redis:
      time-to-live: 3d      # expiration time in cache, supported units: ns, us, ms, s, m, h, d

redis:
  time: 30                  # expiration time in db: must be more 0
  time-unit: days           # unit of expiration time: milliseconds, seconds, minutes, hours or days

rabbitmq:
  exchange: direct-exchange
  routing-key: create-notify-key
  listen-queue: vacancy-save-queue