server:
  port: 0

spring:
  application:
    name: vacancy-storage-service
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888
  profiles:
    active:
    - rabbitmq
    - redis
    - dev

rabbitmq:
  exchange: direct-exchange
  routing-key: create-notify-key
  listen-queue: vacancy-save-queue