server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: rest-api
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: postgresql
  jpa:
    properties:
      hibernate:
        show_sql: true

jwt:
  access-key:
    secret: ZGlzdGFuY2VkcmllZGNvdW50cnlsaWtlbHllaWdodGJyaWVmZmFzdGVyd2VyZXRhbms=
    expiration-time: 24
    expiration-unit: hours
    cookie-name: access_token

search:
  page: 0
  size: 7
  range: 14