server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: rest-api
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888
  profiles:
    active: postgresql, dev