server:
  port: 0
  error:
    include-message: always

spring:
  application:
    name: rest-api
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass
  jpa:
    properties:
      hibernate:
        show_sql: true