server:
  port: 9999
  error:
    include-message: always

spring:
  application:
    name: rate-limiter-service
  config:
    import: optional:configserver:http://localhost:8888

bucket:
  bandwidthMap:
    vacancy-scan-service:
      capacity: 2
      period: PT60S
    telegram-service:
      capacity: 20
      period: PT30S