server:
  port: 9999
  error:
    include-message: always

spring:
  application:
    name: rate-limiter-service
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888
  profiles:
    active: dev