server:
  port: 0

spring:
  application:
    name: vacancy-notifier-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: rabbitmq

rabbitmq:
  exchange: fanout-exchange
  listen-queue: create-notify-queue