server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aojona-config/job-scanner-properties.git
          username: aojona-config
          password: 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
          clone-on-start: true
          basedir: ./config-server/src/main/resources/git
