name: Build, Push And Deploy

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
        
    - name: Build App
      run: ./gradle-build.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Analytic Service
      uses: docker/build-push-action@v5
      with:
        context: ./analytic-service/
        push: true
        tags: ${{ github.repository }}-analytic-service:latest

    - name: Build and Push Config Server
      uses: docker/build-push-action@v5
      with:
        context: ./config-server/
        push: true
        tags: ${{ github.repository }}-config-server:latest

    - name: Build and Push Job Server
      uses: docker/build-push-action@v5
      with:
        context: ./job-server/
        push: true
        tags: ${{ github.repository }}-job-server:latest

    - name: Build and Push Rate Limiter Service
      uses: docker/build-push-action@v5
      with:
        context: ./rate-limiter-service/
        push: true
        tags: ${{ github.repository }}-rate-limiter-service:latest

    - name: Build and Push Rest API
      uses: docker/build-push-action@v5
      with:
        context: ./rest-api/
        push: true
        tags: ${{ github.repository }}-rest-api:latest

    - name: Build and Push Scheduler Service
      uses: docker/build-push-action@v5
      with:
        context: ./scheduler-service/
        push: true
        tags: ${{ github.repository }}-scheduler-service:latest

    - name: Build and Push Telegram Service
      uses: docker/build-push-action@v5
      with:
        context: ./telegram-service/
        push: true
        tags: ${{ github.repository }}-telegram-service:latest

    - name: Build and Push Vacancy Notifier Service
      uses: docker/build-push-action@v5
      with:
        context: ./vacancy-notifier-service/
        push: true
        tags: ${{ github.repository }}-vacancy-notifier-service:latest

    - name: Build and Push Vacancy Scan Service
      uses: docker/build-push-action@v5
      with:
        context: ./vacancy-scan-service/
        push: true
        tags: ${{ github.repository }}-vacancy-scan-service:latest

    - name: Build and Push Vacancy Storage Service
      uses: docker/build-push-action@v5
      with:
        context: ./vacancy-storage-service/
        push: true
        tags: ${{ github.repository }}-vacancy-storage-service:latest

    - name: Build and Push Web UI
      uses: docker/build-push-action@v5
      with:
        context: ./web-ui/
        push: true
        tags: ${{ github.repository }}-web-ui:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Make Env File
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_BOT_NAME: ${{ secrets.BOT_NAME }}
        envkey_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        file_name: .env
        directory: "./"
        fail_on_empty: false
        sort_keys: false

    - name: Pull Images
      run: docker-compose -f docker-compose-prod.yml pull

    - name: Start Services
      run: docker-compose -f docker-compose-prod.yml up -d
